"""initial schema

Revision ID: d9459b74b7d6
Revises: 
Create Date: 2026-09-18 15:29:56.605841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9459b74b7d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('threshold_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_analysis',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('specialists', sa.JSON(), nullable=False),
    sa.Column('symbol_kind', sa.String(length=10), nullable=True),
    sa.Column('identity', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('market_news_feed_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_reasoning', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_news_items_published_date'), 'market_news_items', ['published_date'], unique=False)
    op.create_index(op.f('ix_market_news_items_symbol'), 'market_news_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_news_items_url_hash'), 'market_news_items', ['url_hash'], unique=False)
    op.create_index('ix_market_news_symbol_published', 'market_news_items', ['symbol', 'published_date'], unique=False)
    op.create_index('ix_market_news_url_hash_symbol', 'market_news_items', ['url_hash', 'symbol'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'symbol', name='uq_watchlist_items_watchlist_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_table('watchlists')
    op.drop_table('users')
    op.drop_index('ix_market_news_url_hash_symbol', table_name='market_news_items')
    op.drop_index('ix_market_news_symbol_published', table_name='market_news_items')
    op.drop_index(op.f('ix_market_news_items_url_hash'), table_name='market_news_items')
    op.drop_index(op.f('ix_market_news_items_symbol'), table_name='market_news_items')
    op.drop_index(op.f('ix_market_news_items_published_date'), table_name='market_news_items')
    op.drop_table('market_news_items')
    op.drop_table('market_news_feed_state')
    op.drop_table('company_analysis')
    op.drop_table('alert_configs')
    # ### end Alembic commands ###
