"""add refresh lock to company_analysis

Revision ID: dea8d530e3b2
Revises: d9459b74b7d6
Create Date: 2026-09-19 10:54:07.969612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea8d530e3b2'
down_revision: Union[str, Sequence[str], None] = 'd9459b74b7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_analysis', sa.Column('refresh_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_analysis', 'refresh_started_at')
    # ### end Alembic commands ###
